### ISSUE TITLE
Wait lol what is the df file in the root of the repo?

### ISSUE THREAD

**Issue by DonutsInBelly** [dominusbelli/CS214-SystemsProgramming#1]
https://github.com/dominusbelli/CS214-SystemsProgramming/blob/master/df

??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by DonutsInBelly** [comment]
oh wait is it like a git diff you didon the repo?

**Comment by nomasaur** [comment]
yes
